### ISSUE TITLE
ModuleNotFoundError: No module named 'urllib2'

### ISSUE THREAD

**Issue by webnautics** [alcnsahin/ansible-soap-request#1]
Hey Alican, thanks so much for this soap request implemention, I found no other out there!

But it is not running under my environment:
ansible [core 2.11.3]
Python 3.9.6

It would be really nice if you could help me fixing it!

Here the full traceback:

> The full traceback is:  
> Traceback (most recent call last):  
>   File "/Users/smer/.ansible/tmp/ansible-tmp-1630052721.975007-64130-149039512525984/AnsiballZ_soap_request.py", line 100, in <module>  
>     _ansiballz_main()  
>   File "/Users/smer/.ansible/tmp/ansible-tmp-1630052721.975007-64130-149039512525984/AnsiballZ_soap_request.py", line 92, in _ansiballz_main  
>     invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)  
>   File "/Users/smer/.ansible/tmp/ansible-tmp-1630052721.975007-64130-149039512525984/AnsiballZ_soap_request.py", line 40, in invoke_module  
>     runpy.run_module(mod_name='ansible.modules.soap_request', init_globals=dict(_module_fqn='ansible.modules.soap_request', _modlib_path=modlib_path),  
>   File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 210, in run_module  
>     return _run_module_code(code, init_globals, run_name, mod_spec)  
>   File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code  
>     _run_code(code, mod_globals, init_globals,  
>   File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code  
>     exec(code, run_globals)  
>   File "/var/folders/sr/r_41sd7s0hs2cks2ntd8nmnm0000gp/T/ansible_soap_request_payload_h42fpkm2/ansible_soap_request_payload.zip/ansible/modules/soap_request.py", line 70, in <module>  
> ModuleNotFoundError: No module named 'urllib2'  
> fatal: [localhost]: FAILED! => {  
>     "changed": false,  
>     "module_stderr": "Traceback (most recent call last):\n  File \"/Users/smer/.ansible/tmp/ansible-tmp-1630052721.975007-64130-149039512525984/AnsiballZ_soap_request.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/Users/smer/.ansible/tmp/ansible-tmp-1630052721.975007-64130-149039512525984/AnsiballZ_soap_request.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/smer/.ansible/tmp/ansible-tmp-1630052721.975007-64130-149039512525984/AnsiballZ_soap_request.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.soap_request', init_globals=dict(_module_fqn='ansible.modules.soap_request', _modlib_path=modlib_path),\n  File \"/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/sr/r_41sd7s0hs2cks2ntd8nmnm0000gp/T/ansible_soap_request_payload_h42fpkm2/ansible_soap_request_payload.zip/ansible/modules/soap_request.py\", line 70, in <module>\nModuleNotFoundError: No module named 'urllib2'\n",  
>     "module_stdout": "",  
>     "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",  
>     "rc": 1  
> }  
>

**Comment by alcnsahin** [comment]
Hi Sven,

Sorry for the late response. You cannot use urllib2 because urllib2 is no longer available in Python 3. I redeveloped the module for python 3.

Please reclone the repo and change the **soap_request_py3.py** file to **soap_request.py**. The file is under the library folder. 

I also added a YML example for py3. You can re-edit the file for your API.

And then run the following command;

`ansible-playbook -i localhost soap-request-py3.yml`

I'm waiting for your feedback.

Thanks,
Alican.
